# ==========================================
# APPLICATION
# ==========================================
spring.application.name=backend

# ==========================================
# SERVER
# ==========================================
server.port=8081

# ==========================================
# POSTGRESQL
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/cholera_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# JPA / HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# ==========================================
# SQL INITIALIZATION
# ==========================================
spring.sql.init.mode=always

# ==========================================
# ACTUATOR
# ==========================================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.env.show-values=always

# ==========================================
# LOGGING
# ==========================================
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ==========================================
# PREDICTION SERVICE
# ==========================================
prediction.service.url=http://localhost:8000

# ==========================================
# FILE UPLOAD
# ==========================================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB